"""Type stubs for the _credish C extension."""

from typing import Any, Optional

# The db handle is an opaque capsule
class _Store: ...
_SessionHandle = _Store | tuple[_Store, int]

def open(
    data_dir: str = ".",
    persistence: str = "hybrid",
    save_interval: int = 300,
    aof_fsync: str = "everysec",
    db: int = 0,
) -> _Store: ...

def close(handle: _SessionHandle) -> None: ...
def ping(handle: _SessionHandle) -> str: ...
def flushdb(handle: _SessionHandle) -> bool: ...
def dbsize(handle: _SessionHandle, db: int = 0) -> int: ...
def save(handle: _SessionHandle) -> bool: ...
def bgsave(handle: _SessionHandle) -> bool: ...
def select(handle: _SessionHandle, db: int) -> bool: ...

# String
def get(handle: _SessionHandle, key: str | bytes) -> bytes | None: ...
def get_encoding(handle: _SessionHandle, key: str | bytes) -> int | None: ...
def set(
    handle: _SessionHandle,
    key: str | bytes,
    value: str | bytes | int | float,
    ex: int = -1,
    px: int = -1,
    nx: bool = False,
    xx: bool = False,
    value_encoding: int = 0,
) -> bool | None: ...
def delete(handle: _SessionHandle, keys: list[str | bytes]) -> int: ...
def exists(handle: _SessionHandle, keys: list[str | bytes]) -> int: ...
def expire(handle: _SessionHandle, key: str | bytes, seconds: int) -> bool: ...
def pexpire(handle: _SessionHandle, key: str | bytes, milliseconds: int) -> bool: ...
def persist(handle: _SessionHandle, key: str | bytes) -> bool: ...
def ttl(handle: _SessionHandle, key: str | bytes) -> int: ...
def pttl(handle: _SessionHandle, key: str | bytes) -> int: ...
def type_(handle: _SessionHandle, key: str | bytes) -> str: ...
def incrby(handle: _SessionHandle, key: str | bytes, amount: int) -> int: ...

# List
def lpush(handle: _SessionHandle, key: str | bytes, values: list[Any]) -> int: ...
def rpush(handle: _SessionHandle, key: str | bytes, values: list[Any]) -> int: ...
def lrange(handle: _SessionHandle, key: str | bytes, start: int, stop: int) -> list[bytes]: ...
def llen(handle: _SessionHandle, key: str | bytes) -> int: ...
