name: Wheel builder

on:
  push:
  pull_request:

    paths-ignore:
      - '**.md'
      - '**.rst'
      - '**.pyi'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheel ${{ matrix.python }}-${{ matrix.buildplat[1] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          # - [ubuntu-22.04, manylinux_x86_64]
          # - [ubuntu-22.04-arm, manylinux_aarch64]
          # - [macos-15-intel, macosx_x86_64]
          # - [macos-14, macosx_arm64]
          - [windows-2022, win_amd64]
        python: ["cp312"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.buildplat[1] == 'manylinux_aarch64'
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          CIBW_ARCHS_LINUX: ${{ matrix.buildplat[1] == 'manylinux_aarch64' && 'aarch64' || 'x86_64' }}
          CIBW_ARCHS_MACOS: ${{ matrix.buildplat[1] == 'macosx_arm64' && 'arm64' || 'x86_64' }}
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_BUILD_FRONTEND: "${{ matrix.buildplat[1] == 'win_amd64' && 'build; args: --no-isolation' || 'build' }}"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD_WINDOWS: 'python -m pip install --upgrade "setuptools>=68" wheel'

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
          path: ./wheelhouse/*.whl
